In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

## 1. DataLoader() to change dataset to a chunk of a batch_size

### 1.1 Eg 1

In [2]:
train_dataset = [i for i in range(10)]
train_dataset

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
train_loader = DataLoader(
    dataset=train_dataset, 
    batch_size=3, 
    shuffle=True,
    num_workers=0, 
    pin_memory=True)

train_loader

In [4]:
for data in train_loader:
    print(data)

tensor([6, 7, 9])
tensor([0, 5, 8])
tensor([4, 2, 1])
tensor([3])


### 1.2 Eg 2

In [5]:
train_dataset = ([1, 2], 
                 [3, 4], 
                 [5, 6], 
                 [7, 8], 
                 [9, 10])
train_dataset

([1, 2], [3, 4], [5, 6], [7, 8], [9, 10])

In [6]:
train_loader = DataLoader(
    dataset=train_dataset, 
    batch_size=3, 
    shuffle=True,
    num_workers=0, 
    pin_memory=True)

train_loader

In [7]:
for data in train_loader:
    print(data)

[tensor([9, 3, 5]), tensor([10,  4,  6])]
[tensor([1, 7]), tensor([2, 8])]
